#specify where the remote code base is located (ex: a repo on github)
remote-path: null
#specify where to look for the local code base (ex: working directory)
local-path: "~/.legoHDL/"
#specify a text editor command to open projects for active development
text-editor: "code"