active-workspace: myWorkspace
author: 'Chase Ruskin: double-bladed lightsaber wielder'
editor: code
label:
  IP:
  - .xci
  - true
  SV:
  - .sv
  - false
  TEST-GEN:
  - testbench.py
  - false
market:
  cluster1: https://gitlab.com/chase800/stack.git
  clusterMain: local
  open-market: https://gitlab.com/chase800/open-market.git
script:
  master: '"python3 /Users/Chase/.legohdl/scripts/master.py"'
  mk: '"make -f /Users/Chase/.legohdl/scripts/mk"'
  quick-build: '"python3 /Users/Chase/.legohdl/scripts/quick-build.py"'
  runnr: '"python3 /Users/Chase/.legohdl/scripts/runnr.py"'
workspace:
  myWorkspace:
    local: /Users/Chase/develop/hdl-dev/
    market:
    - cluster1
    - open-market
  myWorkspace2:
    local: /Users/Chase/develop/hdl-op/side/
    market: []
  otherWorkspace:
    local: /Users/Chase/develop/hdl-new/
    market: []
