active-workspace: myWorkspace
author: 'Chase Ruskin: double-bladed lightsaber wielder'
build:
  master: '"python3 /Users/Chase/.legohdl/scripts/master.py"'
  mk: '"make -f /Users/Chase/.legohdl/scripts/mk"'
  runnr: '"python3 /Users/Chase/.legohdl/scripts/runnr.py"'
editor: code
label:
  IP:
  - .xci
  - true
  SV:
  - .sv
  - false
  TEST-GEN:
  - testbench.py
  - false
remote:
  test_rm: https://github.com/c-rus/autoEDA.git
workspace:
  myWorkspace:
    local: /Users/Chase/develop/hdl-dev/
    remote:
    - test_rm
  myWorkspace2:
    local: /Users/Chase/develop/hdl-op/side/
    remote: []
  otherWorkspace:
    local: /Users/Chase/develop/hdl-new/
    remote: []
