active-workspace: myWorkspace
author: 'Chase Ruskin: double-bladed lightsaber wielder'
build:
  maker: '"make -f ''/Users/Chase/develop/hdl-dev/util/ram/makefile''"'
  master: '"python3 /Users/Chase/.legohdl/scripts/master.py"'
  zybo_xdc: '"''/Users/Chase/develop/hdl-dev/util/ram/makefile''"'
editor: code
label:
  IP:
  - .xci
  - true
  TEST-GEN:
  - testbench.py
  - false
workspace:
  myWorkspace:
    local: /Users/Chase/develop/hdl-dev/
    remote: []
  newWork:
    local: /Users/Chase/develop/hdl-dev/
    remote: []
