name: build
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
          with:
            python-version: '3.5'
      - run: pip install -e .
      - run: legohdl