name: build
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.2.2
      - uses: actions/checkout@v2
      - run: pip install .
      - run: legohdl
      - run: y